version: '3'
services:
  db:
    image: mariadb
    container_name: "db"
    networks: 
      - my_network
    ports:
      - "3306:3306"
    restart: always      
    volumes:  
      - ./db/:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
  adminer:
    image: adminer
    container_name: "adminer"
    links: 
      - db
    networks:
      - my_network
    restart: always
    ports:
      - 8080:8080
networks: 
  my_network:
    driver: bridge